#!/usr/bin/python3
import sys

def safe_function(fct, *args):
    try:
        return fct(*args)
    except exception as error:
        print("Exception: {}".format(error), file=sys.stderr)
